name=input("Enter name:" )
clas=input("Enter class:" )
e=input("Mark in english:" )
t=input("Mark in tamil:")
m=input("Mark in maths:")
p=input("Mark in science:")
s=input("Mark in social:")
print(" Name: ",name)
print(" class: ",clas)
print(" english: ",e)
print(" tamil: ",t)
print(" maths: ",m)
print(" science",p)
print(" social",s)
